name: "Repository Request"
description: "Request a new GitHub repository"
title: "[Repo Request] <Your Repository Name>"
labels: [repo-creation]
body:
  - type: dropdown
    id: team_naming
    attributes:
      label: "Team Naming Convention"
      description: "Select the prefix based on your team or organization."
      options:
        - "lifeworks"
        - "telushealth"
    validations:
      required: true

  - type: input
    id: repo_name
    attributes:
      label: "Repository Name"
      description: "Enter the name of the new repository. Prefix will be added based on team naming convention."
      placeholder: "my-awesome-repo"
    validations:
      required: true

  - type: dropdown
    id: default_branch
    attributes:
      label: "Default Branch"
      description: "Select the default branch for your repository."
      options:
        - "main"
        - "develop"
    validations:
      required: true

  - type: dropdown
    id: include_readme
    attributes:
      label: "Include README"
      description: "Would you like to include a README file?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    id: visibility
    attributes:
      label: "Repository Visibility"
      description: "Choose the visibility of the repository."
      options:
        - "private"
        - "internal"
        - "public"
    validations:
      required: true

  - type: textarea
    id: code_owner
    attributes:
      label: "Repository Code Owner(s)"
      description: "Provide the GitHub username(s) of the user(s) you want to add as code owners. Separate multiple usernames with commas."
      placeholder: "e.g. @octocat, @username"
    validations:
      required: true
