name: "Repository Request"
description: "Request a new GitHub repository"
title: "[Repo Request] <Your Repository Name>"
labels: [repo-creation]
body:
  - type: input
    id: repo_name
    attributes:
      label: "Repository Name"
      description: "Enter the name of the new repository."
      placeholder: "my-awesome-repo"
    validations:
      required: true
  
  - type: dropdown
    id: default_branch
    attributes:
      label: "Default Branch"
      description: "Select the default branch for your repository."
      options:
        - "main"
        - "develop"
    validations:
      required: true
  
  - type: dropdown
    id: include_readme
    attributes:
      label: "Include README"
      description: "Would you like to include a README file?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: visibility
    attributes:
      label: "Repository Visibility"
      description: "Choose the visibility of the repository."
      options:
        - "private"
        - "internal"
        - "public"
    validations:
      required: true