name: Team Request
description: Request a new GitHub team
title: "[Team] TEAM-Name"
labels: ["team-request"]
body:
  - type: input
    id: team_name
    attributes:
      label: "Team Name"
      description: "Must start with 'TEAM-' and be 5-25 characters"
      placeholder: "TEAM-backend"
    validations:
      required: true
      pattern: "^TEAM-[a-zA-Z0-9_-]{3,20}$"
  
  - type: dropdown
    id: visibility
    attributes:
      label: "Visibility"
      options: ["Visible", "Secret"]
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: "Purpose"
    validations:
      required: true

  - type: input
    id: maintainers
    attributes:
      label: "Maintainers (comma-separated)"
      placeholder: "user1,user2"
    validations:
      required: true
      pattern: "^[a-z0-9_-]+(,[a-z0-9_-]+)*$"
