name: Team Request
description: Request a new GitHub team
title: "[TEAM] TEAM-Name"
labels: ["team-request"]
body:
  - type: input
    id: team_name
    attributes:
      label: "Team Name"
      description: "Must start with 'TEAM-' and be 5-25 characters"
      placeholder: "TEAM-backend"
    validations:
      required: true
      pattern: "^TEAM-[a-zA-Z0-9_-]{1,20}$"

  - type: input
    id: parent_team
    attributes:
      label: "Parent Team (optional)"
      description: "Provide the parent team name (must exist in the org)"
      placeholder: "team-platform"
    validations:
      required: false
      pattern: "^[a-zA-Z0-9_-]*$"

  - type: dropdown
    id: visibility
    attributes:
      label: "Visibility"
      options: ["Visible", "Secret"]
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: "Purpose"
    validations:
      required: false

  - type: input
    id: maintainers
    attributes:
      label: "Maintainers (comma-separated)"
      description: "Include GitHub usernames or teams (e.g., user1,@org/team1)"
      placeholder: "user1,user2,@org/team1"
    validations:
      required: false
      pattern: "^(@?[a-z0-9_.-]+(/[a-z0-9_.-]+)?)(,\\s*@?[a-z0-9_.-]+(/[a-z0-9_.-]+)?)*$"

  - type: input
    id: team_members
    attributes:
      label: "Team Members (comma-separated)"
      description: "List additional team members (e.g., user3,user4,@org/team2)"
      placeholder: "user3,user4,@org/team2"
    validations:
      required: false
      pattern: "^(@?[a-z0-9_.-]+(/[a-z0-9_.-]+)?)(,\\s*@?[a-z0-9_.-]+(/[a-z0-9_.-]+)?)*$"

  - type: input
    id: full_names
    attributes:
      label: "GitHub User Full Names (comma-separated)"
      description: "Enter full names for all maintainers and members (e.g., John Doe,Jane Smith)"
      placeholder: "John Doe,Jane Smith"
    validations:
      required: true
      pattern: "^([A-Za-z ,.'-]{3,100})(,\\s*[A-Za-z ,.'-]{3,100})*$"
