name: Team Request
description: Request a new GitHub team
title: "[Team] TEAM-Name"
labels: ["team-request"]
body:
  - type: input
    id: team_name
    attributes:
      label: "Team Name"
      description: "Must start with 'TEAM-' and be 5-25 characters"
      placeholder: "TEAM-backend"
    validations:
      required: true
      pattern: "^TEAM-[a-zA-Z0-9_-]{3,20}$"
  
  - type: dropdown
    id: visibility
    attributes:
      label: "Visibility"
      options: ["Visible", "Secret"]
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: "Purpose"
    validations:
      required: true

  - type: input
    id: maintainers
    attributes:
      label: "Maintainers (comma-separated)"
      description: "Include GitHub usernames or teams (e.g., user1,@org/team1)"
      placeholder: "user1,user2,@org/team1"
    validations:
      required: true
      pattern: "^(@?[a-z0-9_.-]+(/[a-z0-9_.-]+)?)(,\\s*@?[a-z0-9_.-]+(/[a-z0-9_.-]+)?)*$"

  - type: input
    id: team_members
    attributes:
      label: "Team Members (comma-separated)"
      description: "List additional team members (e.g., user3,user4,@org/team2)"
      placeholder: "user3,user4,@org/team2"
    validations:
      required: false
      pattern: "^(@?[a-z0-9_.-]+(/[a-z0-9_.-]+)?)(,\\s*@?[a-z0-9_.-]+(/[a-z0-9_.-]+)?)*$"

  - type: input
    id: parent_team
    attributes:
      label: "Parent Team (optional)"
      description: "If this team should be nested under another, provide the parent team's slug"
      placeholder: "team-platform"
    validations:
      required: false
      pattern: "^[a-zA-Z0-9_-]*$"